# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rssole < Formula
  desc "An RSS Reader inspired by the late Google Reader."
  homepage "https://github.com/TheMightyGit/rssole/"
  version "0.1.4"
  depends_on :linux

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TheMightyGit/rssole/releases/download/v0.1.4/rssole_Linux_arm64.tar.gz"
      sha256 "9d6fc4cba8fdbaae111502136f51a90739f08c2d4bb881831ab5f0e00e2fe3c8"

      def install
        bin.install "rssole"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/TheMightyGit/rssole/releases/download/v0.1.4/rssole_Linux_x86_64.tar.gz"
      sha256 "484c1c8766c6618067a39cead664302706d5b69f87ffc88d50b2e9ef2d57872a"

      def install
        bin.install "rssole"
      end
    end
  end
end
